@Library('BranchingPOC') _
pipeline {
   agent any
   parameters {
    stashedFile 'SOD-Tickets'
  }
   
   stages {
        stage('Example') {
      steps {
      
        unstash 'SOD-Tickets'
        sh 'cat SOD-Tickets'
      }
    }
       
   }
  }
