@Library('BranchingPOC') _
pipeline {
   agent any
   parameters {
    stashedFile 'SOD-Tickets'
  }
   
   stages {
        stage('Example') {
      steps {
      
        unstash 'SOD-Tickets'
         script{
         def data = sh (script: "cat SOD-Tickets", returnStdout: true) 
         echo 'this is SOD Hash'
            sh 'git fetch --all'
            def commitHash = sh (script: "git log --pretty=%H --since=2.weeks --grep=${data}", returnStdout: true)  
         println data
         println commitHash
            sh 'git checkout Release'
            sh (script: "git cherry-pick ${commitHash}", returnStdout: true) 
            echo "start deploy job...."
            sh 'git push'

            
         }
        
      }
    }
       
   }
  }
