@Library('BranchingPOC') _
pipeline {
  triggers {
    GenericTrigger(
     genericVariables: [
      [key: 'ref', value: '$.review.state']
     ],

     token: 'review',
    
    )
  }
    agent any
    environment {
        CURRENT_USER = null
        QA_USER = credentials('Jenkins_QA_User')
        QA_CONSUMER_KEY = credentials('QA_CONSUMER_KEY')
        
    }
    stages {
        stage('Init') {
            steps {
              
                script {
                    toolbelt =  tool 'toolbelt' 
                    bot = load "Jenkins/JenkinsHelper.groovy"
                    slackBuilder = load "Jenkins/JenkinsSlackHelper.groovy"
                    PipeGovernor allowsToDeployTo: "QA-Merge"
                    
                }
            }
            
        }

        
    }
}
